### ISSUE TITLE
Examine why pvc provisioning fails in kind (kind-local-5)

### ISSUE THREAD

**Issue by tom1299** [CICDior/fleet-infra#1]
PVC definition:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-test-2
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
```
